# Generated by Django 4.2.10 on 2024-02-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(blank=True, max_length=256, null=True, verbose_name='Пакет')),
                ('tour', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тур')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер вопроса в пакете')),
                ('question_type', models.CharField(choices=[('Б', 'Брейн-ринг'), ('ДБ', 'Брейн-ринг (детский)'), ('И', 'Вопросы из интернета'), ('Л', 'Бескрылка'), ('Ч', 'Что-где-когда'), ('ЧБ', 'Что-где-когда (тренировки)'), ('ЧД', 'Что-где-когда (детский)'), ('Э', 'Эрудитка'), ('Я', 'Своя игра')], db_index=True, default=('Ч', 'Что-где-когда'), max_length=2, verbose_name='Тип вопроса')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('answer', models.TextField(verbose_name='Ответ на вопрос')),
                ('pass_criteria', models.TextField(blank=True, null=True, verbose_name='Критерий правильности ответа')),
                ('authors', models.TextField(blank=True, null=True, verbose_name='Автор(ы) вопроса')),
                ('sources', models.TextField(blank=True, null=True, verbose_name='Источник')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарий к ответу')),
                ('condemned', models.BooleanField(db_index=True, default=False, verbose_name='Вопрос исключен из выдачи')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Вопрос опубликован')),
            ],
            options={
                'verbose_name': 'вопросы из Базы',
                'verbose_name_plural': 'Вопросы из Базы',
            },
        ),
    ]
