# Generated by Django 4.2.10 on 2024-03-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('id',), 'verbose_name': 'вопросы из Базы', 'verbose_name_plural': 'Вопросы из Базы'},
        ),
    ]
