# Generated by Django 4.2.10 on 2024-06-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_condemned',
            field=models.BooleanField(default=False, verbose_name='Вопрос исключен из выдачи'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Вопрос опубликован'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(db_index=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Б', 'Брейн-ринг'), ('ДБ', 'Брейн-ринг (детский)'), ('И', 'Вопросы из интернета'), ('Л', 'Бескрылка'), ('Ч', 'Что-где-когда'), ('ЧБ', 'Что-где-когда (тренировки)'), ('ЧД', 'Что-где-когда (детский)'), ('Э', 'Эрудитка'), ('Я', 'Своя игра')], default=('Ч', 'Что-где-когда'), max_length=2, verbose_name='Тип вопроса'),
        ),
    ]
