version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: arm64v8/postgres:15
    restart: always
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  
  redis:
    image: arm64v8/redis:7
    restart: always
    env_file: ../.env

  backend:
    image: whtn01z/dj_brain_system_backend
    env_file: ../.env
    volumes:
      - static:/app/production_static/
      - media:/app/media/
    depends_on:
      - db
      - redis
  
  tg_bot:
    image: whtn01z/dj_brain_system_bot
    env_file: ../.env
    restart: always
    depends_on:
      - db

  nginx:
    image: whtn01z/dj_brain_system_nginx
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - db
      - backend
      - redis
