version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:15
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    build: ../dj_brain_system/
    env_file: ../.env
    volumes:
      - static:/app/production_static/
      - media:/app/media/
    depends_on:
      - db
  
  tg_bot:
    build: ../telegram_bot/
    env_file: ../.env
    restart: always
    depends_on:
      - db

  nginx:
    build: ./
    ports:
      - "80:80"
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - db
      - backend