# Generated by Django 4.2.10 on 2024-02-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, help_text='Если вы хотите, чтобы вам ответили - заполните это поле', max_length=254)),
                ('feedback_text', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сообщения')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
