# Generated by Django 4.2.10 on 2024-03-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-date',), 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
