# Generated by Django 4.2.10 on 2024-02-29 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtInProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название детали', max_length=64, verbose_name='Название')),
                ('quantity', models.PositiveSmallIntegerField(help_text='Количество:', verbose_name='Количество')),
                ('product_type', models.CharField(blank=True, help_text='Тип', max_length=128, verbose_name='Тип')),
                ('comment', models.CharField(blank=True, help_text='Комментрий', max_length=512, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Покупная деталь',
                'verbose_name_plural': 'Покупные детали',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BoughtInProductAsAPartOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Деталь входит в состав:', max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Покупная деталь в составе',
                'verbose_name_plural': 'Покупные детали в составе',
            },
        ),
        migrations.CreateModel(
            name='BoughtInProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, help_text='Ссылка на деталь', max_length=300, null=True, verbose_name='URL-адрес')),
                ('link_short_name', models.CharField(blank=True, help_text='Короткое название ссылки для таблицы на сайте', max_length=128, null=True, verbose_name='Короткое название ссылки')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_for_product', to='brain_system.boughtinproduct', verbose_name='Объект ссылки')),
            ],
            options={
                'verbose_name': 'Ссылка на покупную деталь',
                'verbose_name_plural': 'Ссылки на покупные детали',
            },
        ),
        migrations.AddField(
            model_name='boughtinproduct',
            name='a_part_of',
            field=models.ForeignKey(help_text='Деталь входит в состав:', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_as_a_part_of', to='brain_system.boughtinproductasapartof', verbose_name='В составе'),
        ),
    ]
