# Generated by Django 4.2.10 on 2024-06-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoughtInProductAsAPartOf',
            new_name='Unit',
        ),
        migrations.RenameField(
            model_name='boughtinproduct',
            old_name='a_part_of',
            new_name='unit',
        ),
    ]
